//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa.Web082022.QTKD.Multilayer.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.Web082022.QTKD.Multilayer.Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete to database return 0.
        /// </summary>
        public static string DevMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("DevMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có  lỗi mã nhân viên trùng nhau.
        /// </summary>
        public static string DevMsg_DuplicateCode {
            get {
                return ResourceManager.GetString("DevMsg_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có  lỗi Exception.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get to database return 0.
        /// </summary>
        public static string DevMsg_GetFailed {
            get {
                return ResourceManager.GetString("DevMsg_GetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert to database return 0.
        /// </summary>
        public static string DevMsg_InsertFailed {
            get {
                return ResourceManager.GetString("DevMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update  to database return 0.
        /// </summary>
        public static string DevMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("DevMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input bỏ trống các trường bắt buộc.
        /// </summary>
        public static string DevMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("DevMsg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;https://openapi.misa.com.vn/errorcode/e002&quot;,.
        /// </summary>
        public static string MoreInfo_DeleteFailed {
            get {
                return ResourceManager.GetString("MoreInfo_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;https://openapi.misa.com.vn/errorcode/e003&quot;,.
        /// </summary>
        public static string MoreInfo_DuplicateCode {
            get {
                return ResourceManager.GetString("MoreInfo_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;https://openapi.misa.com.vn/errorcode/e001&quot;,.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;https://openapi.misa.com.vn/errorcode/e002&quot;,.
        /// </summary>
        public static string MoreInfo_GetFailed {
            get {
                return ResourceManager.GetString("MoreInfo_GetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;https://openapi.misa.com.vn/errorcode/e002&quot;,.
        /// </summary>
        public static string MoreInfo_InsertFailed {
            get {
                return ResourceManager.GetString("MoreInfo_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;https://openapi.misa.com.vn/errorcode/e002&quot;,.
        /// </summary>
        public static string MoreInfo_UpdateFailed {
            get {
                return ResourceManager.GetString("MoreInfo_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_DeleteByID_{0}.
        /// </summary>
        public static string Proc_DeleteByID {
            get {
                return ResourceManager.GetString("Proc_DeleteByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Employee_GetByEmployeeID.
        /// </summary>
        public static string Proc_Employee_GetByEmployeeID {
            get {
                return ResourceManager.GetString("Proc_Employee_GetByEmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Filter_Employee.
        /// </summary>
        public static string Proc_Filter_Employee {
            get {
                return ResourceManager.GetString("Proc_Filter_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetAll_{0}.
        /// </summary>
        public static string Proc_GetAll {
            get {
                return ResourceManager.GetString("Proc_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetByID_{0}.
        /// </summary>
        public static string Proc_GetByID {
            get {
                return ResourceManager.GetString("Proc_GetByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetMaxEmpCode_Employee.
        /// </summary>
        public static string Proc_GetMaxEmpCode_Employee {
            get {
                return ResourceManager.GetString("Proc_GetMaxEmpCode_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Insert_{0}.
        /// </summary>
        public static string Proc_Insert {
            get {
                return ResourceManager.GetString("Proc_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Update_{0}.
        /// </summary>
        public static string Proc_Update {
            get {
                return ResourceManager.GetString("Proc_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi không thành công .
        /// </summary>
        public static string UserMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("UserMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được trùng nhau.
        /// </summary>
        public static string UserMsg_DuplicateCode {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra .Vui lòng liên hệ Misa.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bản ghi nào.
        /// </summary>
        public static string UserMsg_GetFailed {
            get {
                return ResourceManager.GetString("UserMsg_GetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công.
        /// </summary>
        public static string UserMsg_InsertFailed {
            get {
                return ResourceManager.GetString("UserMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa không thành công.
        /// </summary>
        public static string UserMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("UserMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("UserMsg_ValidateFailed", resourceCulture);
            }
        }
    }
}
